{% set version = "1.3.5" %}

package:
  name: lkml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lkml/lkml-{{ version }}.tar.gz
  sha256: 79db845c4fd02d07048fe9e5bf8c49ed5752cd5ab7bc72228791c698c8af2547

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - lkml = lkml.__init__:cli

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

# test_* which use fixtures not in PyPI sdist
{% set skips = [
  "absence_of_debug_flag_is_parsed_to_log_level_warn",
  "block_with_multiple_quoted_fields",
  "block_with_nested_block",
  "block_with_single_quoted_field",
  "debug_flag_is_parsed_to_log_level_debug",
  "duplicate_non_top_level_keys",
  "duplicate_top_level_keys",
  "lists_with_comma_configurations",
  "model_with_all_fields",
  "reserved_dimension_names",
  "view_with_all_fields",
] %}

test:
  source_files:
    - tests
    - setup.cfg
  imports:
    - lkml
  commands:
    - pip check
    - lkml --help
    - coverage run --source=lkml --branch -m pytest -vv --tb=long --color=yes -k "not ({{ skips | join(' or ') }})"
    - coverage report --show-missing --skip-covered --fail-under=90
  requires:
    - pip
    - pytest
    - coverage

about:
  home: https://github.com/joshtemple/lkml
  summary: A speedy LookML parser implemented in pure Python.
  license: MIT
  license_file: LICENSE.md
  doc_url: https://lkml.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
